version: '3.7'

networks:
  default:
    name: ${PROJECT}

volumes:
  dbdata:
    name: ${PROJECT}-mysql

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile-${PHP_VERSION}
      target: bitrix
      args:
       UID: ${UID}
       GID: ${GID}
    container_name: ${PROJECT}-php-${PHP_VERSION}
    volumes:
      - ./system/php:/var/www/log
      - ./htdocs:/var/www/bitrix
    env_file:
      - .env.bitrix

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: ${PROJECT}-nginx
    volumes:
      - ./system/nginx:/var/log/nginx
      - ./htdocs:/var/www/bitrix
    env_file:
      - .env.bitrix
    ports:
      - "${EXT_PORT}:80"

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile-${MYSQL_VERSION}
    container_name: ${PROJECT}-mysql-${MYSQL_VERSION}
    volumes:
      - ./system/mysql/:/tmp/log
      - dbdata:/var/lib/mysql
    env_file:
      - .env.bitrix
      - .env
